version: '3.8'

services:
  node-app:
    image: jinny1/movie-streaming-backend-nodejs:latest
    container_name: node-app
    environment:
      DB_HOST: 13.232.102.107
      DB_USER: admin
      DB_PASSWORD: redhat
      DB_NAME: movie_db
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY:  ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ap-south-1
    ports:
      - "3000:3000"
    depends_on:
      mysql-db:
        condition: service_healthy

  web:
    image: jinny1/movie-streaming-frontend:latest
    container_name: web
    environment:
      API_URL: 13.232.102.107
    ports:
      - "80:80"

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: movie_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: redhat
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  mysql-data:

